# Generated by Django 5.2.6 on 2025-09-04 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OddsScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bet_type", models.CharField(max_length=255)),
                (
                    "payout_multiplier",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("active_from", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("range_min", models.IntegerField(default=1)),
                ("range_max", models.IntegerField(default=99)),
                ("draw_interval_sec", models.IntegerField()),
                ("lock_offset_sec", models.IntegerField()),
                ("min_bet", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_bet", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "odds_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="games.oddsscheme",
                    ),
                ),
            ],
        ),
    ]
