# Generated by Django 5.2.6 on 2025-09-04 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("draws", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selection", models.PositiveSmallIntegerField()),
                ("stake", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "potential_payout",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                            ("VOID", "Void"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("ticket_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="draws.draw"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
