# Generated by Django 5.2.6 on 2025-09-04 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Draw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("locked_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLOSED", "Closed"),
                            ("RESULTED", "Resulted"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("seed_commit_hash", models.CharField(max_length=64)),
                (
                    "seed_reveal",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "winning_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="games.gameconfig",
                    ),
                ),
            ],
        ),
    ]
